# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f38a1a3b8e60c51f1578de13565e86cf7e44c45f5a94b3e3fb5868253f2d202d120005c85076fccb5ad0ff563c25dfb37e6346f81cb0950d34cfe66f35e1217

test:
  secret_key_base: 68588b8325f31bbd32449a3f29edb747aad6b593118b6c255fdadfb3bfad207b104bbde7dd3ed654a0a5bf88921667ca57f4042798d4e32d3fce334932244621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
